### ISSUE TITLE
OpenJTalk.speak()を実行すると、「内部エラー：構造体へのポインタがnullです。」と表示される

### ISSUE THREAD

**Issue by taa829** [rarafy/OpenJTalkForUnity#1]
Unity 2020.3.30f1を使用
サンプルスクリプトを実行すると「内部エラー：構造体へのポインタがnullです。」と出力され発音されません。

**Comment by rarafy** [comment]
@taa829 さん

Issueありがとうございます。
当方でも確認してみますので、恐れ入りますが

・導入方法（.unitypackage / Package Manager）
・書いたスクリプト（または実行したシーン）
・エラーのスクリーンショット
・ご使用のOS

をお送り頂けますでしょうか。手元のUnity2020.3.12f1（Windows）では正常に動いています・・・

**Comment by taa829** [comment]
導入方法はダウンロードしたunitypackageをドラッグ＆ドロップ、
スクリプトはサンプルのSpeak.csです。
使用しているOSは、Windows10 Pro 20H2です。
内部エラーを無視するようコードを書き変えても音響モデルファイルを設定できませんと表示されてしまいます...
![bandicam 2022-03-07 22-22-34-348](https://user-images.githubusercontent.com/64528088/157057343-89fa508c-1d78-4e60-a858-f21951026cc6.jpg)

**Comment by rarafy** [comment]
手元のWindows３台で動作検証してみたのですが、全部正しく動きました。なんでなんでしょう・・・

・導入した段階で何かエラーが出ていましたか？
・他にエラーは出ていませんか？

もし良かったらギガファイル便ででも、プロジェクト送ってください。


追記
今のところ、①バージョン違い（Unity 2020.x）と②.NET関連のパッケージの有無の線が濃い気がしてます。

**Comment by taa829** [comment]
インポートした時点でDLL関連のエラーが3つほどでていましたが、しばらくすると表示が消えました。
問題のプロジェクトファイルのDLリンクです。
DLキーは2525です。
https://57.gigafile.nu/0315-jea384a3edba70aa1a9e645f30e4374b0

**Comment by rarafy** [comment]
こちらの通り、なぜか動きます。バージョンも揃えたので、 @taa829 さんとの環境の違いの可能性が高そうです。
もう少し追跡してみようと思いますので、エラーの全文貼っていただけますと幸いです。

https://user-images.githubusercontent.com/33755507/157063505-57d59e93-98f4-4e8c-86d1-d3ec8b210194.mp4

**Comment by taa829** [comment]
確かにちゃんと動いてますね...
エラーの全文とはこれでいいですかね...？
.NET関係はUnity以外でもよく使うのでしっかり入れてあるはずなんですが...
Unityのバージョンが3つくらい同居してるのもダメなんですかね...

Exception: 内部エラー：構造体へのポインタがnullです。
JTalkDll.JTalkTTS.check_openjtalk_object () (at Assets/OpenJTalkForUnity/Scripts/jtalk.cs:274)
JTalkDll.JTalkTTS..ctor (System.String voicePath, System.String dicPath, System.String voiceDirPath) (at Assets/OpenJTalkForUnity/Scripts/jtalk.cs:76)
OpenJTalk..cctor () (at Assets/OpenJTalkForUnity/Scripts/OpenJTalk.cs:18)
Rethrow as TypeInitializationException: The type initializer for 'OpenJTalk' threw an exception.
Speak.Start () (at Assets/OpenJTalkForUnity/_Scene/Speak.cs:11)

**Comment by rarafy** [comment]
このプロジェクトが置かれているパスに日本語や半角スペースは含まれていませんか？
検証環境は64bitコンピュータ＋64bit OSですか？

**Comment by rarafy** [comment]
たしか、C#用の .dllパッケージを64bit向けにビルドした記憶があります。

64bitでしたら、エラー自体はjtalk.csの73行目で出ているので、コンストラクタの全パラメータを人力で指定する解決方法もあります。ログを見る限り、このどれかのパラメータがおかしくなってる気がします。
![image](https://user-images.githubusercontent.com/33755507/157070577-677257f7-8f44-4990-a880-06274157a3cf.png)

**Comment by taa829** [comment]
環境は64bit PCに64bit OSなので大丈夫なはずなんですが...
パスもD:/VChara　となっているので日本語は含まれていないはずです...
.NET系の何かが足りないんでしょうか...

**Comment by rarafy** [comment]
うーん、 .NET系で考えられるとすればDotNet SDKですかね。

①念の為、これを入れてみてもらっても良いでしょうか？（あまり原因に直接関係はなさそうですが）
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.200-windows-x64-installer

② こちらのパッケージを解凍して
https://github.com/rosmarinus/jtalkdll/releases/download/v0.0.63/jtalkdllx64-0.0.63.zip
c:\open_jtalk となるようにCドライブ直下に中のファイルを展開して頂けますでしょうか。

③その上で、システムの詳細設定で環境変数PATHにc:\open_jtalk\binを追加してみてください。

以上３点ともやってみて、どうにもならなかったらパス直打ちを試してみましょう。

**Comment by rarafy** [comment]
あとは念の為、

① こちらのパッケージを解凍して
https://github.com/rosmarinus/jtalkdll/releases/download/v0.0.63/jtalkdllx64-0.0.63.zip

c:\open_jtalk となるようにCドライブ直下に中のファイルを展開して頂けますでしょうか。

②その上で、システムの詳細設定で環境変数PATHにc:\open_jtalk\binを追加してみてください。

以上３点ともやってみて、どうにもならなかったらパス直打ちを試してみましょう。

**Comment by rarafy** [comment]
もし別のPCが用意できれば、[この方法（UnityPackageを使う方法）](https://rarafy.com/blog/2022/03/03/openjtalk-for-unity/)で新規プロジェクト を作って検証してみてください。環境によるものもあるのかもしれません。

Windows Serverでも動いたので、この差はきっと環境によるものに違いないとは思うのですが、どこに原因があるんでしょうかね。

![image](https://user-images.githubusercontent.com/33755507/157270202-50a9c306-465c-456c-ba64-2a0450a09968.png)

**Comment by rarafy** [comment]
Windows Serverでも動いたので、きっと環境によるものに違いないとは思うのですが、どこに原因があるんでしょうかね。
![image](https://user-images.githubusercontent.com/33755507/157270202-50a9c306-465c-456c-ba64-2a0450a09968.png)

**Comment by taa829** [comment]
別のPCで試してみたところ、しっかりしゃべってくれました。
やっぱりメインで使ってるPCの環境がおかしいみたいですね...
.NET SDKをインストールしたりファイル展開してパスも追加したんですがやはりnullだと表示されてしまいます...

**Comment by rarafy** [comment]
うーん、なんでなんでしょう。もし原因解明出来ましたら、どうか教えてください。
むしろREADMEとかに書いてください。これであなたも共同作者に・・・

個人的にはJTalkTTSの３つのパラメータを自前で宣言した場合の挙動も気になるところです。

**Comment by taa829** [comment]
もしかしたらUniVRMと一緒に使用しているのが原因かもしれないので一旦プロジェクトを作り直してみます。
UniVRMがなにか悪さをしてるかもしれません...
JTalkTTSのパラメーターを指定するのも試してみますね。

**Comment by taa829** [comment]
jtalk.csのJTalkTTSのパラメーターを手動で設定してあげたところ、しっかりしゃべってくれました！！

**Comment by rarafy** [comment]
おお！良かったです。
ちなみに後学のためにどのように設定したかご教示いただけますでしょうか。

**Comment by taa829** [comment]
jtalk.csの73行目をこう設定しました。
voicePathは後からスクリプトで変更できるのでなんでもいいみたいです。
`
public JTalkTTS(String voicePath = "mei_happy", String dicPath = "Assets/OpenJTalkForUnity/dll/dic_utf_8", String voiceDirPath = "Assets/OpenJTalkForUnity/dll/voice")
`

**Comment by taa829** [comment]
ところでしゃべってる途中にすべての動作が止まってしまうんですが、これも不具合ですかね？

**Comment by rarafy** [comment]
相対パスで行けたんですね。ありがとうございます。

**Comment by rarafy** [comment]
しゃべってる途中にすべての動作が止まってしまう件ですが、これは仕様です（とりあえず動かしたいという人が多いのでサンプルは必要最小限だけ書いています）。
対処方法は、非同期の「タスク」という機能になります。
簡単なサンプルは、[この記事](https://rarafy.com/blog/2022/03/03/openjtalk-for-unity/)の下の方、「補足１．非同期で動かしたい」に載せていますので参考にしてみてください。

追記
あとはサンプルに含まれる、Stoppable.unity というシーンが確かタスクを使って途中停止させていたと思います。ご参考まで

**Comment by taa829** [comment]
ありがとうございます！無事解決しました！
